<!-- Languages -->
<ul
	class="uiList ptm localeSelectorList_mini _4ki clearfix _6-h _6-i _6-j">
	<li class="uiListItem"><a title="English (US)"
		onclick="intl_set_cookie_locale(&quot;en_US&quot;, &quot;http:\/\/www.facebook.com\/index.php?stype=lo&amp;lh=Ac-gzumoaGpXXgiG&quot;);"
		href="http://www.facebook.com/index.php?stype=lo&amp;lh=Ac-gzumoaGpXXgiG"
		dir="ltr">English (US)</a></li>
	<li class="plm uiListItem"><a title="Vietnamese"
		onclick="intl_set_cookie_locale(&quot;vi_VN&quot;, &quot;http:\/\/vi-vn.facebook.com\/index.php?stype=lo&amp;lh=Ac-gzumoaGpXXgiG&quot;);"
		href="http://vi-vn.facebook.com/index.php?stype=lo&amp;lh=Ac-gzumoaGpXXgiG"
		dir="ltr">Tiếng Việt</a></li>
</ul>
