<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ProjectName')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/style6.css')
                    ->prependStylesheet($this->basePath() . '/css/style5.css')
                    ->prependStylesheet($this->basePath() . '/css/style4.css')
                    ->prependStylesheet($this->basePath() . '/css/style3.css')
                    ->prependStylesheet($this->basePath() . '/css/style2.css')                    
                    ->prependStylesheet($this->basePath() . '/css/style1.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')
                                  ->prependFile($this->basePath() . '/js/acc.js') ?>

  </head>
  <body class="fbIndex UIPage_LoggedOut ff4 win Locale_en_US">
	  <div class="_li">
	      <?php echo $this->content; ?>
	  	
	  </div>
  </body>
</html>
