<div class="menu_login_container">
  					<form id="login_form" name="login_form" method="post" action="/account/login">				  						
  						<table cellspacing="0">
  							<tbody>
  								<tr>
  									<td class="html7magic"><label for="email"><?php echo $this->translate('Email or Phone') ?></label></td>
  									<td class="html7magic"><label for="pass"><?php echo $this->translate('Password')?></label></td>
  								</tr>
  								<tr>
  									<td><input type="text" tabindex="1" value="" id="email" name="email" class="inputtext"></td>
  									<td><input type="password" tabindex="2" id="pass" name="pass" class="inputtext"></td>
  									<td>
  										<label for="ua04id44" id="loginbutton" class="uiButton uiButtonConfirm">
  										<input type="submit" id="ua04id44" tabindex="4" value="<?php echo $this->translate('Log In')?>"></label>
  									</td>
  								</tr>
  								<tr>
  									<td class="login_form_label_field">
  										<div class="uiInputLabel clearfix">
  											<input type="checkbox" class="uiInputLabelCheckbox" tabindex="3" value="1" name="persistent" id="persist_box">
  											<label for="persist_box"><?php echo $this->translate('Keep me logged in')?></label>
  										</div>
  										<input type="hidden" value="0" name="default_persistent">
  									</td>
  									<td class="login_form_label_field">
  										<a href="#" rel="nofollow"><?php echo $this->translate('Forgot your password?')?></a>
  									</td>
  								</tr>
  							</tbody>
  						</table>				  						
  					</form>
</div>