<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/7zbnWIn5KVK.css.css')
                    ->prependStylesheet($this->basePath() . '/css/K8GNgvsW4l1.css')
                    ->prependStylesheet($this->basePath() . '/css/u8iA3kXb8Y1.css')
                    ->prependStylesheet($this->basePath() . '/css/GTnvb0JRdwO.css')
                    ->prependStylesheet($this->basePath() . '/css/Er3Qn9s0aPi.css')                    
                    ->prependStylesheet($this->basePath() . '/css/8e04id9zUP-.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>

  </head>
  <body>
	  <div class="_li">
	  	<!-- Header -->
	  	<div data-referrer="pagelet_bluebar" id="pagelet_bluebar">
	  		<div id="blueBarHolder">
	  			<div id="blueBar">
	  				<div class="loggedout_menubar_container">
		  				<div class="clearfix loggedout_menubar">
		  					<a title="Go to Facebook Home" href="/" class="lfloat">
		  						<i class="fb_logo img sp_1zq7t7 sx_082ee8"><u>Facebook logo</u></i>
		  					</a>
			  				<div class="rfloat">
				  				<div class="menu_login_container">
				  					<form method="post" action="https://www.facebook.com/login.php?login_attempt=1" id="login_form">
				  						<input type="hidden" autocomplete="off" value="AVoJejCB" name="lsd">
				  						<table cellspacing="0">
				  							<tbody>
				  								<tr>
				  									<td class="html7magic"><label for="email">Email or Phone</label></td>
				  									<td class="html7magic"><label for="pass">Password</label></td>
				  								</tr>
				  								<tr>
				  									<td><input type="text" tabindex="1" value="" id="email" name="email" class="inputtext"></td>
				  									<td><input type="password" tabindex="2" id="pass" name="pass" class="inputtext"></td>
				  									<td>
				  										<label for="ua04id44" id="loginbutton" class="uiButton uiButtonConfirm">
				  										<input type="submit" id="ua04id44" tabindex="4" value="Log In"></label>
				  									</td>
				  								</tr>
				  								<tr>
				  									<td class="login_form_label_field">
				  										<div class="uiInputLabel clearfix">
				  											<input type="checkbox" class="uiInputLabelCheckbox" tabindex="3" value="1" name="persistent" id="persist_box">
				  											<label for="persist_box">Keep me logged in</label>
				  										</div>
				  										<input type="hidden" value="0" name="default_persistent">
				  									</td>
				  									<td class="login_form_label_field">
				  										<a href="http://www.facebook.com/recover.php" rel="nofollow">Forgot your password?</a>
				  									</td>
				  								</tr>
				  							</tbody>
				  						</table>
				  						<input type="hidden" value="€,´,€,´,水,Д,Є" name="charset_test">
				  						<input type="hidden" id="ua04id43" value="-420" name="timezone" autocomplete="off">
				  						<input type="hidden" value="102525_Xtza" name="lgnrnd">
				  						<input type="hidden" value="1348593924" name="lgnjs" id="lgnjs">
				  						<input type="hidden" value="en_US" name="locale" id="locale" autocomplete="off">
				  					</form>
				  				</div>
			  				</div>
		  				</div>
	  				</div>
	  			</div>
	 		</div>
		</div>
		
		<div class="uiContextualLayerParent" id="globalContainer">
		<!-- Panel Left -->
		<!-- Panel Right -->
		<!-- Footer -->
		</div>
	  </div>
  </body>
</html>