
<!-- Footer -->
<div data-referrer="page_footer" id="pageFooter">
    <div id="contentCurve"></div>
    <div id="footerContainer" class="clearfix">
    	<div class="mrl lfloat">
    		<div class="fsm fwn fcg">
    			<span> <?php echo $this->translate('ProjectName')?> &copy; 2012</span> · <a title="<?php echo $this->translate('Use ProjectName in another language.')?>" href="#" >English (US)</a>
    		</div>
    	</div>
    	<div class="navigation fsm fwn fcg">
    		<a title="<?php echo $this->translate('Review our terms and policies.')?>" href="#"><?php echo $this->translate('Term')?></a> · <a title="<?php echo $this->translate('Visit our Help Center.')?>" href="#"><?php echo $this->translate('Help')?></a>
    	</div>
    </div>
</div>
		