<div data-referrer="page_footer" id="pageFooter">
	<div id="contentCurve"></div>
	<div id="footerContainer" class="clearfix">
		<div class="mrl lfloat">
			<div class="fsm fwn fcg">
				<span> Facebook &copy; 2012</span> · <a role="button"
					title="Use Facebook in another language."
					href="http://www.facebook.com/ajax/intl/language_dialog.php?uri=http%3A%2F%2Fwww.facebook.com%2Fhome.php%3Fref%3Dlogo"
					rel="dialog">English (US)</a>
			</div>
		</div>
		<div aria-label="Facebook site links" role="contentinfo"
			class="navigation fsm fwn fcg">
			<a
				title="Read our blog, discover the resource center, and find job opportunities."
				accesskey="8" href="http://www.facebook.com/facebook">About</a> · <a
				title="Advertise on Facebook."
				href="http://www.facebook.com/campaign/landing.php?placement=pf&amp;campaign_id=402047449186&amp;extra_1=auto">Create
				an Ad</a> · <a title="Create a Page"
				href="http://www.facebook.com/pages/create.php?ref_type=sitefooter">Create
				a Page</a> · <a title="Develop on our platform."
				href="http://developers.facebook.com/?ref=pf">Developers</a> · <a
				title="Make your next career move to our awesome company."
				href="http://www.facebook.com/careers/?ref=pf">Careers</a> · <a
				title="Learn about your privacy and Facebook."
				href="http://www.facebook.com/privacy/explanation">Privacy</a> · <a
				title="Learn about cookies and Facebook."
				href="http://www.facebook.com/help/cookies">Cookies</a> · <a
				title="Review our terms and policies." accesskey="9"
				href="http://www.facebook.com/policies/?ref=pf">Terms</a> · <a
				title="Visit our Help Center." accesskey="0"
				href="http://www.facebook.com/help/?ref=pf">Help</a>
		</div>
	</div>
</div>