<div data-referrer="pagelet_bluebar" id="pagelet_bluebar">
	<div class="slim" id="blueBarHolder">
		<div class="fixed_elem" id="blueBar">
			<div class="clearfix" id="pageHead">
				<h1 id="pageLogo">
					<a href="http://www.facebook.com/?ref=logo" style="">ProjectName</a>
				</h1>
				<div class="notifNegativeBase notifCentered notifGentleAppReceipt"
					id="jewelContainer">
					<div id="fbRequestsJewel"
						class="fbJewel hasNew hasCountMedium showRequests">
						
					</div>
					<div id="fbMessagesJewel" class="fbJewel">
						
					</div>
					<div id="fbNotificationsJewel" class="fbJewel west">
						
					</div>
				</div>
				<div id="headNav" class="clearfix">
					<form name="navSearch" id="navSearch" method="get" class="lfloat">
						<div id="ubypmma2" class="uiTypeahead">
							<div class="wrap">								
								<div class="innerWrap">
									<span id="ubypmma3" class="uiSearchInput textInput"><span><input
											type="text" value="Search for people, places and things"
											spellcheck="false" onfocus="$(&quot;search_first_focus&quot;).value = $(&quot;search_first_focus&quot;).value || +new Date();;Bootloader.loadComponents(&quot;SearchBootloader&quot;, emptyFunction);"
											tabindex="" autocomplete="off"
											placeholder="Search for people, places and things"
											onclick="var q = $(&quot;q&quot;);if (q.value == q.getAttribute(&quot;placeholder&quot;)) {q.focus(); return false;}"
											name="q" id="q" accesskey="/" aria-label="Search"
											maxlength="100" class="inputtext DOMControl_placeholder">
											<button title="Search for people, places and things"
												onclick="var q = $(&quot;q&quot;);if (q.value == q.getAttribute(&quot;placeholder&quot;)) {q.focus(); return false;}"
												type="submit">
												<span class="accessible_elem">Search for people, places and
													things</span>
											</button></span></span>
								</div>
							</div>
							<div id="ubypmma1"
								class="uiTypeaheadView wideSearchTypeaheadView mainSearchTypeaheadView"></div>
						</div>
					</form>
					<div class="rfloat">
						<ul role="navigation" class="clearfix" id="pageNav">
							<li class="navItem firstItem tinyman"><a accesskey="2"
								title="Profile"
								href="http://www.facebook.com/bui.thanhphuong.3?ref=tn_tnmn"
								class="navLink"><img id="profile_pic_header_100000235183823"
									alt=""
									src="%2891%29%20Facebook_files/202907_100000235183823_5803336_q.jpg"
									class="_s0 headerTinymanPhoto _rw img"><span
									class="headerTinymanName">Bui Thanh Phuong</span></a></li>
							<li class="navItem middleItem"><a id="findFriendsNav"
								href="http://www.facebook.com/?sk=ff" class="navLink bigPadding">Find
									Friends</a></li>
							<li id="navHome" class="navItem middleItem"><a accesskey="1"
								href="http://www.facebook.com/?ref=tn_tnmn"
								class="navLink bigPadding">Home</a></li>
							<li id="navAccount"><a aria-labelledby="userNavigationLabel"
								aria-controls="userNavigation" aria-haspopup="1" role="button"
								rel="toggle"
								href="http://www.facebook.com/editaccount.php?ref=mb&amp;drop"
								id="navAccountLink" class="navLink"><div
										id="userNavigationLabel" class="menuPulldown">Account Settings</div></a>
								<ul aria-label="Account Menu" role="menu navigation"
									id="userNavigation" class="navigation">
									<li role="menuitem"><a
										href="http://www.facebook.com/campaign/landing.php?placement=tad&amp;campaign_id=264263327005748&amp;extra_1=auto&amp;extra_2=AdvertisingMenu%3ACONTROL"
										class="navSubmenu">Advertise</a></li>
									<li role="menuitem"><a accesskey="6"
										href="http://www.facebook.com/editaccount.php?ref=mb&amp;drop"
										class="navSubmenu">Account Settings</a></li>
									<li role="menuitem"><a accesskey="7"
										href="http://www.facebook.com/settings/?tab=privacy&amp;ref=mb"
										class="navSubmenu">Privacy Settings</a></li>
									<li role="menuitem"><form
											onsubmit="return window.Event &amp;&amp; Event.__inlineSubmit &amp;&amp; Event.__inlineSubmit(this,event)"
											action="http://www.facebook.com/logout.php" method="post"
											id="logout_form">
											<input type="hidden" autocomplete="off" value="AQDQF8w2"
												name="fb_dtsg"><input type="hidden" value="mb" name="ref"
												autocomplete="off"><input type="hidden"
												value="AfchoXD2CgC6oXXa" name="h" autocomplete="off"><label
												class="uiLinkButton navSubmenu"><input type="submit"
												value="Log Out"></label>
										</form></li>
									<li class="menuDivider"></li>
									<li role="menuitem"><a rel="async"
										ajaxify="http://www.facebook.com/help/ajax/contextual/?page_type=364455653583099"
										target="_blank" id="navHelpCenter"
										href="http://www.facebook.com/help/?ref=drop"
										class="navSubmenu"><div class="clearfix">
												<div class="lfloat">Help</div>
												<img width="16" height="11" alt=""
													src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
													class="rfloat uiLoadingIndicatorAsync img">
											</div></a></li>
								</ul></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>