<div data-referrer="pagelet_bluebar" id="pagelet_bluebar">
	<div class="slim" id="blueBarHolder">
		<div class="fixed_elem" id="blueBar">
			<div class="clearfix" id="pageHead">
				<h1 id="pageLogo">
					<a href="http://www.facebook.com/?ref=logo" style="">ProjectName</a>
				</h1>
				<div class="notifNegativeBase notifCentered notifGentleAppReceipt"
					id="jewelContainer">
					<div id="fbRequestsJewel"
						class="fbJewel hasNew hasCountMedium showRequests"></div>
					<div id="fbMessagesJewel" class="fbJewel"></div>
					<div id="fbNotificationsJewel" class="fbJewel west"></div>
				</div>
				<div id="headNav" class="clearfix">
					<form name="navSearch" id="navSearch" method="get" class="lfloat">
						<div id="ubypmma2" class="uiTypeahead">
							<div class="wrap">
								<div class="innerWrap">
									<span id="ubypmma3" class="uiSearchInput textInput"> <span><input
											type="text" value="Search for people, places and things"
											maxlength="100" class="inputtext DOMControl_placeholder">
											<button title="Search for people, places and things"
												type="submit"></button></span></span>
								</div>
							</div>
							<div id="ubypmma1"
								class="uiTypeaheadView wideSearchTypeaheadView mainSearchTypeaheadView"></div>
						</div>
					</form>
					<div class="rfloat">
						<ul class="clearfix" id="pageNav">
							<li class="navItem firstItem tinyman"><a title="Profile" href="#"
								class="navLink"><img id="profile_pic_header_100000235183823"
									alt="" src="/images/avatar_boy.gif"
									class="_s0 headerTinymanPhoto _rw img"><span
									class="headerTinymanName">Bui Thanh Phuong</span></a></li>
							<li class="navItem middleItem"><a id="findFriendsNav" href="#"
								class="navLink bigPadding">Find Friends</a></li>
							<li id="navHome" class="navItem middleItem"><a accesskey="1"
								href="#" class="navLink bigPadding">Home</a></li>
							<li id="navAccount" class=""><a href="#" id="navAccountLink" onclick="menuPullDown();"
								class="navLink"><div id="userNavigationLabel"
										class="menuPulldown">Account Settings</div></a>
								<ul id="userNavigation" class="navigation">
									<li><a href="#" class="navSubmenu">Advertise</a></li>
									<li><a href="#" class="navSubmenu">Account Settings</a></li>
									<li><a href="#" class="navSubmenu">Privacy Settings</a></li>
									<li><form action="#" method="post" id="logout_form">
											<label class="uiLinkButton navSubmenu"><input type="submit"
												value="Log Out"></label>
										</form></li>
									<li class="menuDivider"></li>
									<li><a href="#" class="navSubmenu"><div class="clearfix">
												<div class="lfloat">Help</div>

											</div></a></li>
								</ul></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>