<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
    <?php echo $this->headTitle('ProjectName')->setSeparator(' - ')->setAutoEscape(false)?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

    <!-- Le styles -->
    <?php
    
    echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/favicon.ico'
    ))
        ->prependStylesheet($this->basePath() . '/css/map_style14.css')
        ->prependStylesheet($this->basePath() . '/css/map_style13.css')
        ->prependStylesheet($this->basePath() . '/css/map_style12.css')
        ->prependStylesheet($this->basePath() . '/css/map_style11.css')
        ->prependStylesheet($this->basePath() . '/css/map_style10.css')
        ->prependStylesheet($this->basePath() . '/css/map_style9.css')
        ->prependStylesheet($this->basePath() . '/css/map_style8.css')
        ->prependStylesheet($this->basePath() . '/css/map_style7.css')
        ->prependStylesheet($this->basePath() . '/css/map_style6.css')
        ->prependStylesheet($this->basePath() . '/css/map_style5.css')
        ->prependStylesheet($this->basePath() . '/css/map_style4.css')
        ->prependStylesheet($this->basePath() . '/css/map_style3.css')
        ->prependStylesheet($this->basePath() . '/css/map_style2.css')
        ->prependStylesheet($this->basePath() . '/css/map_style1.css')
        ->prependStylesheet($this->basePath() . '/css/map_style.css')?>

    <!-- Scripts -->
    <?php
    
    echo $this->headScript()
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
    ))
        ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')
        ->prependFile($this->basePath() . '/js/map.js')?>

</head>
<body class="hasLeftCol home composerExpanded fbx ff4 win Locale_en_US"
	onload="initialize()">
	<div class="_li">

		<!-- Header -->		
        <?php echo $this->render('layout/header_map.phtml')?>
		<!-- Content -->
		<div class="uiContextualLayerParent" id="globalContainer">
			<div class="fb_content clearfix" id="content">
				<div>
					<div id="mainContainer">
						<!-- Left Content -->
						<?php echo $this->render('layout/left_content_map.phtml')?>

						<!-- Right Content -->
						<div
							class="homeFixedLayout homeWiderContent hasExpandedComposer newsFeedComposer composerOpen homeFixedLayout hasRightCol"
							id="contentCol" style="min-height: 500px;"
							data-referrer="contentCol">
							
							<?php echo $this->content; ?>
						</div>





					</div>
				</div>
			</div>

			<!-- Footer -->
			<?php echo $this->render('layout/footer_map.phtml')?>
			



		</div>
	</div>

</body>
</html>
