<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
    <?php echo $this->headTitle('ProjectName')->setSeparator(' - ')->setAutoEscape(false)?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

    <!-- Le styles -->
    <?php
    
    echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/favicon.ico'
    ))
        ->prependStylesheet($this->basePath() . '/css/map_style14.css')
        ->prependStylesheet($this->basePath() . '/css/map_style13.css')
        ->prependStylesheet($this->basePath() . '/css/map_style12.css')
        ->prependStylesheet($this->basePath() . '/css/map_style11.css')
        ->prependStylesheet($this->basePath() . '/css/map_style10.css')
        ->prependStylesheet($this->basePath() . '/css/map_style9.css')
        ->prependStylesheet($this->basePath() . '/css/map_style8.css')
        ->prependStylesheet($this->basePath() . '/css/map_style7.css')
        ->prependStylesheet($this->basePath() . '/css/map_style6.css')
        ->prependStylesheet($this->basePath() . '/css/map_style5.css')
        ->prependStylesheet($this->basePath() . '/css/map_style4.css')
        ->prependStylesheet($this->basePath() . '/css/map_style3.css')
        ->prependStylesheet($this->basePath() . '/css/map_style2.css')
        ->prependStylesheet($this->basePath() . '/css/map_style1.css')
        ->prependStylesheet($this->basePath() . '/css/map_style.css')?>

    <!-- Scripts -->
    <?php
    
    echo $this->headScript()
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
    ))
        ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')
        ->prependFile($this->basePath() . '/js/map.js')?>
    
    
   
<style>
#map_canvas {
	margin: 0;
	padding: 0;
	height: 100%;
}
</style>
<script
	src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=visualization">
    </script>
<script>
      var map;

      function initialize() {
        var mapOptions = {
          zoom: 2,
          center: new google.maps.LatLng(2.8,-187.3),
          mapTypeId: google.maps.MapTypeId.TERRAIN
        };
        map = new google.maps.Map(document.getElementById('map_canvas'),
              mapOptions);

        var script = document.createElement('script');
        script.src = 'http://earthquake.usgs.gov/earthquakes/feed/geojsonp/2.5/week';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(script, s);
        
      }

      // Loop through the results array and place a marker for each
      // set of coordinates.
      window.eqfeed_callback = function(results) {
        for (var i = 0; i < results.features.length; i++) {
          var coords = results.features[i].geometry.coordinates;
          var latLng = new google.maps.LatLng(coords[1],coords[0]);
          var marker = new google.maps.Marker({
            position: latLng,
            map: map,
            icon: getCircle(earthquake.properties.mag)
            
          });
        }
      }

  </script>



</head>
<body class="hasLeftCol home composerExpanded fbx ff4 win Locale_en_US"
	onload="initialize()">
	<div class="_li">

		<!-- Header -->		
        <?php echo $this->render('layout/header.phtml')?>
		<!-- Content -->
		<div class="uiContextualLayerParent" id="globalContainer">
			<div class="fb_content clearfix" id="content">
				<div>
					<div id="mainContainer">
						<!-- Left Content -->
						<?php echo $this->render('layout/left_content.phtml')?>

						<!-- Right Content -->
						<div
							class="homeFixedLayout homeWiderContent hasExpandedComposer newsFeedComposer composerOpen homeFixedLayout hasRightCol"
							id="contentCol" style="min-height: 500px;"
							data-referrer="contentCol">
							
							<?php echo $this->content; ?>
						</div>





					</div>
				</div>
			</div>

			<!-- Footer -->
			<?php echo $this->render('layout/footer.phtml')?>
			



		</div>
	</div>

</body>
</html>
