<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
    <?php echo $this->headTitle('ProjectName')->setSeparator(' - ')->setAutoEscape(false)?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

    <!-- Le styles -->
    <?php
    
    echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/favicon.ico'
    ))
        ->prependStylesheet($this->basePath() . '/css/map_style14.css')
        ->prependStylesheet($this->basePath() . '/css/map_style13.css')
        ->prependStylesheet($this->basePath() . '/css/map_style12.css')
        ->prependStylesheet($this->basePath() . '/css/map_style11.css')
        ->prependStylesheet($this->basePath() . '/css/map_style10.css')
        ->prependStylesheet($this->basePath() . '/css/map_style9.css')
        ->prependStylesheet($this->basePath() . '/css/map_style8.css')
        ->prependStylesheet($this->basePath() . '/css/map_style7.css')
        ->prependStylesheet($this->basePath() . '/css/map_style6.css')
        ->prependStylesheet($this->basePath() . '/css/map_style5.css')
        ->prependStylesheet($this->basePath() . '/css/map_style4.css')
        ->prependStylesheet($this->basePath() . '/css/map_style3.css')
        ->prependStylesheet($this->basePath() . '/css/map_style2.css')
        ->prependStylesheet($this->basePath() . '/css/map_style1.css')?>

    <!-- Scripts -->
    <?php
    
    echo $this->headScript()
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
    ))
        ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')?>
    
    
   
<style>
#map_canvas {
	margin: 0;
	padding: 0;
	height: 100%;
}
</style>
<script
	src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=visualization">
    </script>
<script>
      var map;

      function initialize() {
        var mapOptions = {
          zoom: 2,
          center: new google.maps.LatLng(2.8,-187.3),
          mapTypeId: google.maps.MapTypeId.TERRAIN
        };
        map = new google.maps.Map(document.getElementById('map_canvas'),
              mapOptions);

        var script = document.createElement('script');
        script.src = 'http://earthquake.usgs.gov/earthquakes/feed/geojsonp/2.5/week';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(script, s);
        
      }

      // Loop through the results array and place a marker for each
      // set of coordinates.
      window.eqfeed_callback = function(results) {
        for (var i = 0; i < results.features.length; i++) {
          var coords = results.features[i].geometry.coordinates;
          var latLng = new google.maps.LatLng(coords[1],coords[0]);
          var marker = new google.maps.Marker({
            position: latLng,
            map: map,
            icon: getCircle(earthquake.properties.mag)
            
          });
        }
      }

  </script>



</head>
<body class="hasLeftCol home composerExpanded fbx ff4 win Locale_en_US"
	onload="initialize()">
	<div class="_li">

		<!-- Header -->
		<div data-referrer="pagelet_bluebar" id="pagelet_bluebar">
			<div class="slim" id="blueBarHolder">
				<div class="fixed_elem" id="blueBar">
					<div role="banner" class="clearfix" id="pageHead">
						<h1 id="pageLogo">
							<a href="http://www.facebook.com/?ref=logo" style="">Facebook</a>
						</h1>
						<div class="notifNegativeBase notifCentered notifGentleAppReceipt"
							id="jewelContainer">
							<div id="fbRequestsJewel"
								class="fbJewel hasNew hasCountMedium showRequests">
								<a aria-owns="fbRequestsFlyout" aria-haspopup="true"
									data-target="fbRequestsFlyout"
									data-gt="{&quot;ua_id&quot;:&quot;jewel:requests&quot;}"
									name="requests" aria-labelledby="requestsCountWrapper"
									role="button" href="#" rel="toggle" class="jewelButton"><span
									id="requestsCountWrapper" class="jewelCount"><span
										id="requestsCountValue">91</span><i class="accessible_elem">
											Requests</i></span></a>
							</div>
							<div id="fbMessagesJewel" class="fbJewel">
								<a aria-owns="fbMessagesFlyout" aria-haspopup="true"
									data-target="fbMessagesFlyout"
									data-gt="{&quot;ua_id&quot;:&quot;jewel:mercurymessages&quot;}"
									name="mercurymessages"
									aria-labelledby="mercurymessagesCountWrapper" role="button"
									href="#" rel="toggle" class="jewelButton"><span
									id="mercurymessagesCountWrapper" class="jewelCount"><span
										id="mercurymessagesCountValue">0</span><i
										class="accessible_elem"> Messages</i></span></a>
							</div>
							<div id="fbNotificationsJewel" class="fbJewel west">
								<a aria-owns="fbNotificationsFlyout" aria-haspopup="true"
									data-target="fbNotificationsFlyout"
									data-gt="{&quot;ua_id&quot;:&quot;jewel:notifications&quot;}"
									onclick="return run_with(this, [&quot;min-notifications-jewel&quot;], function() {MinNotifications.bootstrap(this)});"
									name="notifications"
									aria-labelledby="notificationsCountWrapper" role="button"
									href="#" rel="toggle" class="jewelButton"><span
									id="notificationsCountWrapper" class="jewelCount"><span
										id="notificationsCountValue">0</span><i
										class="accessible_elem"> Notifications</i></span></a>
							</div>
						</div>
						<div id="headNav" class="clearfix">
							<form
								onsubmit="return window.Event &amp;&amp; Event.__inlineSubmit &amp;&amp; Event.__inlineSubmit(this,event)"
								role="search"
								action="http://www.facebook.com/search/results.php"
								name="navSearch" id="navSearch" method="get" class="lfloat">
								<div id="ubypmma2" class="uiTypeahead">
									<div class="wrap">
										<input type="hidden" class="hiddenInput" autocomplete="off">
										<div class="innerWrap">
											<span id="ubypmma3" class="uiSearchInput textInput"><span><input
													type="text" value="Search for people, places and things"
													spellcheck="false" role="combobox"
													aria-owns="typeahead_list_ubypmma2" aria-expanded="false"
													aria-autocomplete="list"
													onfocus="$(&quot;search_first_focus&quot;).value = $(&quot;search_first_focus&quot;).value || +new Date();;Bootloader.loadComponents(&quot;SearchBootloader&quot;, emptyFunction);"
													tabindex="" autocomplete="off"
													placeholder="Search for people, places and things"
													onclick="var q = $(&quot;q&quot;);if (q.value == q.getAttribute(&quot;placeholder&quot;)) {q.focus(); return false;}"
													name="q" id="q" accesskey="/" aria-label="Search"
													maxlength="100" class="inputtext DOMControl_placeholder">
													<button title="Search for people, places and things"
														onclick="var q = $(&quot;q&quot;);if (q.value == q.getAttribute(&quot;placeholder&quot;)) {q.focus(); return false;}"
														type="submit">
														<span class="accessible_elem">Search for people, places
															and things</span>
													</button></span></span>
										</div>
									</div>
									<div id="ubypmma1"
										class="uiTypeaheadView wideSearchTypeaheadView mainSearchTypeaheadView"></div>
								</div>
							</form>
							<div class="rfloat">
								<ul role="navigation" class="clearfix" id="pageNav">
									<li class="navItem firstItem tinyman"><a accesskey="2"
										title="Profile"
										href="http://www.facebook.com/bui.thanhphuong.3?ref=tn_tnmn"
										class="navLink"><img id="profile_pic_header_100000235183823"
											alt=""
											src="%2891%29%20Facebook_files/202907_100000235183823_5803336_q.jpg"
											class="_s0 headerTinymanPhoto _rw img"><span
											class="headerTinymanName">Bui Thanh Phuong</span></a></li>
									<li class="navItem middleItem"><a id="findFriendsNav"
										href="http://www.facebook.com/?sk=ff"
										class="navLink bigPadding">Find Friends</a></li>
									<li id="navHome" class="navItem middleItem"><a accesskey="1"
										href="http://www.facebook.com/?ref=tn_tnmn"
										class="navLink bigPadding">Home</a></li>
									<li id="navAccount"><a aria-labelledby="userNavigationLabel"
										aria-controls="userNavigation" aria-haspopup="1" role="button"
										rel="toggle"
										href="http://www.facebook.com/editaccount.php?ref=mb&amp;drop"
										id="navAccountLink" class="navLink"><div
												id="userNavigationLabel" class="menuPulldown">Account
												Settings</div></a>
										<ul aria-label="Account Menu" role="menu navigation"
											id="userNavigation" class="navigation">
											<li role="menuitem"><a
												href="http://www.facebook.com/campaign/landing.php?placement=tad&amp;campaign_id=264263327005748&amp;extra_1=auto&amp;extra_2=AdvertisingMenu%3ACONTROL"
												class="navSubmenu">Advertise</a></li>
											<li role="menuitem"><a accesskey="6"
												href="http://www.facebook.com/editaccount.php?ref=mb&amp;drop"
												class="navSubmenu">Account Settings</a></li>
											<li role="menuitem"><a accesskey="7"
												href="http://www.facebook.com/settings/?tab=privacy&amp;ref=mb"
												class="navSubmenu">Privacy Settings</a></li>
											<li role="menuitem"><form
													onsubmit="return window.Event &amp;&amp; Event.__inlineSubmit &amp;&amp; Event.__inlineSubmit(this,event)"
													action="http://www.facebook.com/logout.php" method="post"
													id="logout_form">
													<input type="hidden" autocomplete="off" value="AQDQF8w2"
														name="fb_dtsg"><input type="hidden" value="mb" name="ref"
														autocomplete="off"><input type="hidden"
														value="AfchoXD2CgC6oXXa" name="h" autocomplete="off"><label
														class="uiLinkButton navSubmenu"><input type="submit"
														value="Log Out"></label>
												</form></li>
											<li class="menuDivider"></li>
											<li role="menuitem"><a rel="async"
												ajaxify="http://www.facebook.com/help/ajax/contextual/?page_type=364455653583099"
												target="_blank" id="navHelpCenter"
												href="http://www.facebook.com/help/?ref=drop"
												class="navSubmenu"><div class="clearfix">
														<div class="lfloat">Help</div>
														<img width="16" height="11" alt=""
															src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
															class="rfloat uiLoadingIndicatorAsync img">
													</div></a></li>
										</ul></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Content -->
		<div class="uiContextualLayerParent" id="globalContainer">
			<div class="fb_content clearfix" id="content">
				<div>
					<div id="mainContainer">
						<!-- Left Content -->
						<div id="leftColContainer">
							<div id="leftCol">
								<div data-referrer="pagelet_welcome_box"
									id="pagelet_welcome_box">
									<div class="clearfix fbxWelcomeBox">
										<a tabindex="-1" aria-hidden="true"
											href="http://www.facebook.com/bui.thanhphuong.3"
											class="fbxWelcomeBoxBlock _8o _8s lfloat"><img
											id="profile_pic_welcome_100000235183823" alt=""
											src="%2891%29%20Facebook_files/202907_100000235183823_5803336_q.jpg"
											class="_s0 fbxWelcomeBoxImg _rw img"></a>
										<div class="_8m ">
											<div class="_6a prs">
												<div style="height: 40px" class="_6a _6b"></div>
												<div class="_6a _6b">
													<a href="http://www.facebook.com/bui.thanhphuong.3"
														class="fbxWelcomeBoxName">Bui Thanh Phuong</a>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div data-referrer="pagelet_navigation" id="pagelet_navigation">
									<div id="sideNav"
										data-gt="{&quot;ref&quot;:&quot;bookmarks&quot;}"
										class="uiFutureSideNav" role="navigation"
										aria-label="Navigation">
										<div id="pagelet_pinned_nav"
											data-referrer="pagelet_pinned_nav">
											<div id="pinnedNav" class="homeSideNav">
												<h4 class="navHeader">FAVORITES</h4>
												<div class="mts mbm droppableNav">
													<ul
														data-gt="{&quot;nav_items_count&quot;:&quot;6&quot;,&quot;nav_section&quot;:&quot;pinnedNav&quot;}"
														class="uiSideNav">
														<li id="navItem_app_156203961126022"
															class="sideNavItem stat_elem"><div class="buttonWrap"></div>
															<a
															data-gt="{&quot;bmid&quot;:&quot;156203961126022&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AauTDzN3uLIi4YHUYt5xZCPIIXZUEl-dTVKhLaHLSxzSq4c_iJzVbKpAZ1EqlFtbxSszLdsQ8Ng6e0tw7nzAMUM9&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;1&quot;}"
															title="" href="http://www.facebook.com/?sk=welcome"
															class="item clearfix"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_1a6dlz sx_b7393d"></i></span>
																	<div class="linkWrap noCount">Welcome</div>
																</div></a></li>
														<li id="navItem_app_4748854339"
															class="sideNavItem stat_elem selectedItem open"><div
																class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit News Feed" title="Edit"
																			role="button" href="#"
																			class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Edit Settings" class="uiMenuItem"><a
																						rel="dialog"
																						href="http://www.facebook.com/ajax/feed/edit_options_dialog.php"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Edit Settings</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;4748854339&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AaurrtxV6m4nhjsG9W1VrY1Hx14r0p-4lwfWJpmRDJ7-2cmto7UVD2jRamkYAWIRHSM&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;2&quot;}"
															title="" href="http://www.facebook.com/?sk=nf"
															class="item clearfix"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_6quz4z sx_9c9117"></i></span>
																	<div class="linkWrap noCount">News Feed</div>
																</div></a></li>
														<li id="navItem_app_217974574879787"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Messages" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Remove from Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Remove from Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;217974574879787&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;2&quot;,&quot;coeff2_info&quot;:&quot;Aav1iT5k4dBbi7k3_BkEKK3F7ZpXMQi0PkyYWjEGEMCsBobNMUU2aemoj-Y5giZKgBS2TlsgpxxoCOhg6uhDmInh&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;3&quot;}"
															title="" href="http://www.facebook.com/messages/"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count uiSideNavCount"><span
																		class="countValue fss">2</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_7uj4ry sx_ada3a2"></i></span>
																	<div class="linkWrap hasCount">Messages</div>
																</div></a>
															<ul>
																<li id="navItem_other"><a
																	href="http://www.facebook.com/messages/other/"
																	class="subitem clearfix"><div class="rfloat">
																			<img width="16" height="11" alt=""
																				src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																				class="uiLoadingIndicatorAsync img"><span
																				class="count uiSideNavCount"><span
																				class="countValue fss">1</span><span
																				class="maxCountIndicator"></span></span>
																		</div>
																		<div>
																			<div class="linkWrap hasCount">Other</div>
																		</div></a></li>
															</ul> <span class="mover hidden_elem"></span></li>
														<li id="navItem_app_2344061033"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Events" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Remove from Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Remove from Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;2344061033&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AausMPS3OW43-lhlox35Eo60m4NY8GUTX-dp3LIg63-UUgV6IOcQSpPPAzN2nBNXQwQ&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;4&quot;}"
															title="" href="http://www.facebook.com/events/list"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><img width="15" height="16"
																		alt="" src="%2891%29%20Facebook_files/vdO3Bhuj5K8.png"
																		class="img"></span>
																	<div class="linkWrap noCount">Events</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_app_2305272732"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Photos" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Remove from Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Remove from Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;2305272732&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AatCCB8gUKbdDzU4_T8RQhx6R-dLTDb3_iiqpXuUBRwjRXXSJpQzQ5WYJHvuflB2I5Y&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;5&quot;}"
															title=""
															href="http://www.facebook.com/bui.thanhphuong.3/photos"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_2vmry3 sx_beccc5"></i></span>
																	<div class="linkWrap noCount">Photos</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_app_2356318349"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Find Friends" title="Edit"
																			role="button" href="#"
																			class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Remove from Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Remove from Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;2356318349&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;91&quot;,&quot;coeff2_info&quot;:&quot;Aavl3D1JH3OaSuqml4T-bbb21Jm5MJMdHuOdmkn2qzyxjprGblN2kbGFUZInnWabKuA&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;6&quot;}"
															title="Find Friends"
															href="http://www.facebook.com/?sk=ff"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count uiSideNavCount"><span
																		class="countValue fss">20</span><span
																		class="maxCountIndicator">+</span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_tiitwu sx_cc1db2"></i></span>
																	<div class="linkWrap hasCount">Find Friends</div>
																</div></a><span class="mover hidden_elem"></span></li>
													</ul>
													<div class="actionLinks stat_elem">
														<a data-endpoint="/ajax/bookmark/edit/" href="#"
															class="navEditDone"><span class="navEdit">Edit</span><span
															class="navDone">Done</span></a><span
															class="loadingIndicator"></span>
													</div>
												</div>
											</div>
										</div>
										<div id="pagelet_bookmark_nav"
											data-referrer="pagelet_bookmark_nav">
											<div>
												<div id="appsNav" class="homeSideNav">
													<h4 class="navHeader">APPS</h4>
													<ul
														data-gt="{&quot;nav_items_count&quot;:&quot;6&quot;,&quot;nav_section&quot;:&quot;appsNav&quot;}"
														class="uiSideNav mts mbm nonDroppableNav">
														<li id="navItem_app_140332009231"
															class="sideNavItem stat_elem expander"><div
																class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit App Center" title="Edit"
																			role="button" href="#"
																			class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;140332009231&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;type&quot;:&quot;click2appcenter&quot;,&quot;coeff2_info&quot;:&quot;Aau5HKfjKZQBE15kK9oEd53CdQuZJgk-8piPmYx8LDNKxSLwD4ROW-wb-iVH1LArkA8BZ-KpdMrvkzKGBlFsNr3a&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;1&quot;}"
															title=""
															href="http://www.facebook.com/appcenter/?from_bookmark=1"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_6quz4z sx_b7e554"></i></span>
																	<div class="linkWrap noCount">App Center</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_app_261369767293002"
															class="sideNavItem stat_elem">
															<div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Games Feed" title="Edit"
																			role="button" href="#"
																			class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;261369767293002&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;10&quot;,&quot;coeff2_info&quot;:&quot;AatWXC2310gxYPgEZ9z2mwptYKePmr_XB1DTjfZ_8VIiWHoG-3uD8CphTSA3h7C39f2Aoy_eMao4fgcEq_Gdq27e&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;2&quot;}"
															title="" href="http://www.facebook.com/apps/feed"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count uiSideNavCount"><span
																		class="countValue fss">10</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_2vmry3 sx_d03f36"></i></span>
																	<div class="linkWrap hasCount">Games Feed</div>
																</div></a><span class="mover hidden_elem"></span>
														</li>
														<li id="navItem_app_119960514742544"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Music" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;119960514742544&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;Aau1nMgtdeEi9b6gWBaXyQG787-hg_jmYegrNXAVav8VXbIrRHDjcbXDKzVZMDFuWnUcD6PZrmWsgyZ90qGSXX0r&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;3&quot;}"
															title="" href="http://www.facebook.com/music"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_2vmry3 sx_21e6a7"></i></span>
																	<div class="linkWrap noCount">Music</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_app_2347471856"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Notes" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;2347471856&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;Aav6Hf_SdCohPruZMK_dKUqec29DkkFchQkZWVcbyrLD3XHGRka78CzxkdP4WVjRdSw&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;4&quot;}"
															title="" href="http://www.facebook.com/notes/"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_2vmry3 sx_eafddd"></i></span>
																	<div class="linkWrap noCount">Notes</div>
																</div></a>
															<ul>
																<li id="navItem_notes_pages"><a
																	href="http://www.facebook.com/notes/pages/"
																	class="subitem clearfix"><div class="rfloat">
																			<img width="16" height="11" alt=""
																				src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																				class="uiLoadingIndicatorAsync img"><span
																				class="count hidden_elem uiSideNavCount"><span
																				class="countValue fss">0</span></span>
																		</div>
																		<div>
																			<div class="linkWrap noCount">Pages' Notes</div>
																		</div></a></li>
																<li id="navItem_notes_drafts"><a
																	href="http://www.facebook.com/notes/drafts/"
																	class="subitem clearfix"><div class="rfloat">
																			<img width="16" height="11" alt=""
																				src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																				class="uiLoadingIndicatorAsync img"><span
																				class="count hidden_elem uiSideNavCount"><span
																				class="countValue fss">0</span></span>
																		</div>
																		<div>
																			<div class="linkWrap noCount">My Drafts</div>
																		</div></a></li>
																<li id="navItem_notes_tagged"><a
																	href="http://www.facebook.com/notes/tagged/"
																	class="subitem clearfix"><div class="rfloat">
																			<img width="16" height="11" alt=""
																				src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																				class="uiLoadingIndicatorAsync img"><span
																				class="count hidden_elem uiSideNavCount"><span
																				class="countValue fss">0</span></span>
																		</div>
																		<div>
																			<div class="linkWrap noCount">Notes About Me</div>
																		</div></a></li>
																<li id="navItem_notes_me"><a
																	href="http://www.facebook.com/notes/me/"
																	class="subitem clearfix"><div class="rfloat">
																			<img width="16" height="11" alt=""
																				src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																				class="uiLoadingIndicatorAsync img"><span
																				class="count hidden_elem uiSideNavCount"><span
																				class="countValue fss">0</span></span>
																		</div>
																		<div>
																			<div class="linkWrap noCount">My Notes</div>
																		</div></a></li>
															</ul> <span class="mover hidden_elem"></span></li>
														<li id="navItem_app_2309869772"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Links" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;2309869772&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;type&quot;:&quot;click2canvas&quot;,&quot;coeff2_info&quot;:&quot;AavBNz4o8rZQZWT7e830u5J4fm7PvOYD2tnNuV9PSM_LXuDLvzShPf2sLnMFy3_mft8&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;5&quot;}"
															title=""
															href="http://www.facebook.com/?sk=app_2309869772"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_2vmry3 sx_a25cf9"></i></span>
																	<div class="linkWrap noCount">Links</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_app_183217215062060"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Pokes" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;183217215062060&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AauH04ot9GLgxX-VKuOMCt5bAYBLdo1It2H_7Gxa0xqwlrSAZbL3vTWFdGSOzNoeJ98c04nVr853qug0-dH7Y8qN&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;6&quot;}"
															title="" href="http://www.facebook.com/pokes"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_6quz4z sx_0bc8e8"></i></span>
																	<div class="linkWrap noCount">Pokes</div>
																</div></a><span class="mover hidden_elem"></span></li>
													</ul>
												</div>
												<div id="groupsNav" class="homeSideNav">
													<h4 class="navHeader">GROUPS</h4>
													<ul
														data-gt="{&quot;nav_items_count&quot;:&quot;4&quot;,&quot;nav_section&quot;:&quot;groupsNav&quot;}"
														class="uiSideNav mts mbm nonDroppableNav">
														<li id="navItem_group_519834054699098"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit H?i nh?ng ngu?i thích an chay"
																			title="Edit" role="button" href="#"
																			class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																					<li data-label="Edit Settings" class="uiMenuItem"><a
																						rel="dialog"
																						href="http://www.facebook.com/ajax/groups/membership/subscribe_get.php?group_id=519834054699098"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Edit Settings</span></a></li>
																					<li class="uiMenuSeparator"></li>
																					<li data-label="Leave Group" class="uiMenuItem"><a
																						rel="dialog"
																						href="http://www.facebook.com/ajax/bookmark/groups/leave/?group_id=519834054699098"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Leave Group</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;519834054699098&quot;,&quot;fbtype&quot;:&quot;69&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AatRBfFQs6JFJEr9P7DBWSA9DoNcLdEyitiFJKFsDbxZc2lB0CJlgRwd3ZQNTVRPBYnsC8PdtlO_BQFORSNRcch5&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;1&quot;}"
															title="H?i nh?ng ngu?i thích an chay"
															href="http://www.facebook.com/groups/vegevill/"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_9sdxgb sx_961b7d"></i></span>
																	<div class="linkWrap noCount">H?i nh?ng ngu?i thích an
																		chay</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_group_167606749934601"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Beeric" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																					<li data-label="Edit Settings" class="uiMenuItem"><a
																						rel="dialog"
																						href="http://www.facebook.com/ajax/groups/membership/subscribe_get.php?group_id=167606749934601"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Edit Settings</span></a></li>
																					<li class="uiMenuSeparator"></li>
																					<li data-label="Leave Group" class="uiMenuItem"><a
																						rel="dialog"
																						href="http://www.facebook.com/ajax/bookmark/groups/leave/?group_id=167606749934601"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Leave Group</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;167606749934601&quot;,&quot;fbtype&quot;:&quot;69&quot;,&quot;count&quot;:&quot;1&quot;,&quot;coeff2_info&quot;:&quot;AauJmCvTtLBtv1rfPokM6F78N9Rou6QhbrxmEaedzQwzBMfZWI24_XO8CoP6_ZcUZviDcDBgY9dvuWo_Xt1u_S1W&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;2&quot;}"
															title=""
															href="http://www.facebook.com/groups/167606749934601/"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count uiSideNavCount"><span
																		class="countValue fss">1</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_7uj4ry sx_056073"></i></span>
																	<div class="linkWrap hasCount">Beeric</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_group_226618834060591"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit H?i nh?ng ngu?i thích tra t?n ngu?i khác b?ng gi?ng ca"
																			title="Edit" role="button" href="#"
																			class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																					<li data-label="Edit Settings" class="uiMenuItem"><a
																						rel="dialog"
																						href="http://www.facebook.com/ajax/groups/membership/subscribe_get.php?group_id=226618834060591"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Edit Settings</span></a></li>
																					<li class="uiMenuSeparator"></li>
																					<li data-label="Leave Group" class="uiMenuItem"><a
																						rel="dialog"
																						href="http://www.facebook.com/ajax/bookmark/groups/leave/?group_id=226618834060591"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Leave Group</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;226618834060591&quot;,&quot;fbtype&quot;:&quot;69&quot;,&quot;count&quot;:&quot;25&quot;,&quot;coeff2_info&quot;:&quot;AavXnFLFkLdgz85mqE1w8rm04wdw6cVm0gIkQnhpYs2Dc07HltQa5F-zIToHv00IWjvtNwseal6upl7BG_5tccOY&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;3&quot;}"
															title="H?i nh?ng ngu?i thích tra t?n ngu?i khác b?ng gi?ng ca"
															href="http://www.facebook.com/groups/226618834060591/"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count uiSideNavCount"><span
																		class="countValue fss">20</span><span
																		class="maxCountIndicator">+</span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_7uj4ry sx_056073"></i></span>
																	<div class="linkWrap hasCount">H?i nh?ng ngu?i thích
																		tra t?n ngu?i khác b?ng gi?ng ca</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_app_230259100322928"
															class="sideNavItem stat_elem"><div class="buttonWrap"></div>
															<a
															data-gt="{&quot;bmid&quot;:&quot;230259100322928&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;Aatctrnx5WmnxOdfe4Open89RWMeUzzDV9CTR7PBVGZqHUqTw2yEnu5pN9oDHxsmCQoBsq9FqRloWxDQYl3emMOZ&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;4&quot;}"
															rel="async" title="Create Group..."
															href="http://www.facebook.com/ajax/groups/create_get.php?ref=bookmarks"
															class="item clearfix"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_6quz4z sx_e60393"></i></span>
																	<div class="linkWrap noCount">Create Group...</div>
																</div></a></li>
													</ul>
												</div>
												<div id="interestsNav" class="homeSideNav">
													<h4 class="navHeader hidden_elem">
														<a href="http://www.facebook.com/bookmarks/interests"><div
																class="clearfix">
																<div class="lfloat">INTERESTS</div>
																<span class="mrm rfloat"><div class="bookmarksNavSeeAll">MORE</div>
																	<img width="16" height="11" alt=""
																	src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																	class="uiLoadingIndicatorAsync img"></span>
															</div></a>
													</h4>
													<ul
														data-gt="{&quot;nav_items_count&quot;:&quot;0&quot;,&quot;nav_section&quot;:&quot;interestsNav&quot;}"
														class="uiSideNav mts mbm nonDroppableNav"></ul>
												</div>
												<div id="pagesNav" class="homeSideNav">
													<h4 class="navHeader">PAGES</h4>
													<ul
														data-gt="{&quot;nav_items_count&quot;:&quot;3&quot;,&quot;nav_section&quot;:&quot;pagesNav&quot;}"
														class="uiSideNav mts mbm nonDroppableNav">
														<li id="navItem_app_140472815972081"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Pages Feed" title="Edit"
																			role="button" href="#"
																			class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;140472815972081&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;3&quot;,&quot;coeff2_info&quot;:&quot;AaueWGtB889rhry4WlSqJ10V-Rad-HCpp1qglssnog5BtnKx-G9JJpUZ-jRy47887ApSshJg8wfg8HYPCVi5L4Om&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;1&quot;}"
															title=""
															href="http://www.facebook.com/pages/feed?ref=bookmarks"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count uiSideNavCount"><span
																		class="countValue fss">3</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><img width="16" height="16"
																		alt="" src="%2891%29%20Facebook_files/pMNap2ngsij.png"
																		class="img"></span>
																	<div class="linkWrap hasCount">Pages Feed</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_app_357937250942127"
															class="sideNavItem stat_elem"><div class="buttonWrap"></div>
															<a
															data-gt="{&quot;bmid&quot;:&quot;357937250942127&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AavDEwfd-8LPW6SAicwocaJNUpAdcnocwtjkEpPTxEPjr_pL78DZ4s9ev2mV2lMNyFBrGwAR-BtCVxmQmKkAJuzO&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;2&quot;}"
															title=""
															href="http://www.facebook.com/pages?ref=bookmarks"
															class="item clearfix"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_6quz4z sx_33fe3c"></i></span>
																	<div class="linkWrap noCount">Like Pages</div>
																</div></a></li>
														<li id="navItem_app_188619144602540"
															class="sideNavItem stat_elem"><div class="buttonWrap"></div>
															<a
															data-gt="{&quot;bmid&quot;:&quot;188619144602540&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AaugXdVSKKinjcrZ7_hP8WYidVTVMkKZ1pOFX8Lc4Giw88Q3u_5dfterTd3lPHe27JagkM4eoRLPbsIYt2aDzqma&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;3&quot;}"
															title="Create a Page..."
															href="http://www.facebook.com/pages/create.php?ref=bookmarks"
															class="item clearfix"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_2vmry3 sx_cc1d2b"></i></span>
																	<div class="linkWrap noCount">Create a Page...</div>
																</div></a></li>
													</ul>
												</div>
												<div id="listsNav" class="homeSideNav belowThreshold">
													<h4 class="navHeader">
														<a href="http://www.facebook.com/bookmarks/lists"><div
																class="clearfix">
																<div class="lfloat">FRIENDS</div>
																<span class="mrm rfloat"><div class="bookmarksNavSeeAll">MORE</div>
																	<img width="16" height="11" alt=""
																	src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																	class="uiLoadingIndicatorAsync img"></span>
															</div></a>
													</h4>
													<ul
														data-gt="{&quot;nav_items_count&quot;:&quot;3&quot;,&quot;nav_section&quot;:&quot;listsNav&quot;}"
														class="uiSideNav mts mbm nonDroppableNav">
														<li id="navItem_fl_478653708819131"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Close Friends" title="Edit"
																			role="button" href="#"
																			class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;478653708819131&quot;,&quot;fbtype&quot;:&quot;17&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AasKPBUeRmMdpMgGltyWJaIptXVVkj77rZUJMxv9FCSsz7rBoNqII_l3y_C4ZXKE8Lbrq4oP_b_Zr2Cr4LKV-aw1&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;1&quot;}"
															title="Close Friends"
															href="http://www.facebook.com/lists/478653708819131"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_6quz4z sx_e34de1"></i></span>
																	<div class="linkWrap noCount">Close Friends</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_fl_478653712152464"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit Family" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																					<li class="uiMenuSeparator"></li>
																					<li data-label="Archive List" class="uiMenuItem"><a
																						rel="dialog"
																						href="http://www.facebook.com/ajax/friends/lists/archive/?flid=478653712152464"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Archive List</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;478653712152464&quot;,&quot;fbtype&quot;:&quot;17&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AavEIOFowh4fyj8BCXVnudVoprnvCvHcmzMtxcvpWW6yKncyW6OQzfoaMF9F9Aj1uRiGBKn1EvW1Wf1blD5CqNhu&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;2&quot;}"
															title=""
															href="http://www.facebook.com/lists/478653712152464"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_6quz4z sx_bdeff5"></i></span>
																	<div class="linkWrap noCount">Family</div>
																</div></a><span class="mover hidden_elem"></span></li>
														<li id="navItem_fl_103837632967409"
															class="sideNavItem stat_elem"><div class="buttonWrap">
																<div
																	class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
																	<div class="wrap">
																		<a rel="toggle" aria-haspopup="1"
																			aria-label="Edit friends" title="Edit" role="button"
																			href="#" class="uiSelectorButton uiCloseButton"></a>
																		<div class="uiSelectorMenuWrapper uiToggleFlyout">
																			<div class="uiMenu uiSelectorMenu" role="menu">
																				<ul class="uiMenuInner">
																					<li data-label="Add to Favorites"
																						class="uiMenuItem favorite"><a href="#"
																						tabindex="0" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Add to Favorites</span></a></li>
																					<li data-label="Rearrange"
																						class="uiMenuItem rearrange"><a href="#"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Rearrange</span></a></li>
																					<li class="uiMenuSeparator"></li>
																					<li data-label="Delete List" class="uiMenuItem"><a
																						rel="dialog"
																						href="http://www.facebook.com/friends/edit/ajax/delete_list_dialog.php?flid=103837632967409"
																						tabindex="-1" role="menuitem" class="itemAnchor"><span
																							class="itemLabel fsm">Delete List</span></a></li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div> <a
															data-gt="{&quot;bmid&quot;:&quot;103837632967409&quot;,&quot;fbtype&quot;:&quot;17&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;Aat42o_RgJCcQOTVQ0rUdXPInl-TDCItfydJVObHPmrNj8wAWXL-fxKvFed_wAG-05k2JfAsSjXX5fxkbY9orj5G&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;3&quot;}"
															title=""
															href="http://www.facebook.com/lists/103837632967409"
															class="item clearfix sortableItem"><div class="rfloat">
																	<img width="16" height="11" alt=""
																		src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
																		class="uiLoadingIndicatorAsync img"><span
																		class="count hidden_elem uiSideNavCount"><span
																		class="countValue fss">0</span><span
																		class="maxCountIndicator"></span></span><span
																		class="grip"></span>
																</div>
																<div>
																	<span class="imgWrap"><i
																		class="img sp_6quz4z sx_a0b389"></i></span>
																	<div class="linkWrap noCount">friends</div>
																</div></a><span class="mover hidden_elem"></span></li>
													</ul>
												</div>
												<a id="ubyptq81" href="#" class="moreSectionsLink"><span
													class="uiMoreLinkText">MORE</span><i
													class="uiMoreLinkCaret img sp_2vmry3 sx_f8318f"></i></a>
											</div>
										</div>
									</div>
								</div>
							</div>







						</div>


						<!-- Right Content -->
						<div
							class="homeFixedLayout homeWiderContent hasExpandedComposer newsFeedComposer composerOpen homeFixedLayout hasRightCol"
							id="contentCol" style="min-height: 100px;"
							data-referrer="contentCol">
							<div id="main_map" style="height: 500px; width:800px;">

								<div id="map_canvas"></div>

							</div>
							<?php echo $this->content; ?>
						</div>





					</div>
				</div>
			</div>

			<!-- Footer -->
			<div data-referrer="page_footer" id="pageFooter">
				<div id="contentCurve"></div>
				<div id="footerContainer" class="clearfix">
					<div class="mrl lfloat">
						<div class="fsm fwn fcg">
							<span> Facebook &copy; 2012</span> · <a role="button"
								title="Use Facebook in another language."
								href="http://www.facebook.com/ajax/intl/language_dialog.php?uri=http%3A%2F%2Fwww.facebook.com%2Fhome.php%3Fref%3Dlogo"
								rel="dialog">English (US)</a>
						</div>
					</div>
					<div aria-label="Facebook site links" role="contentinfo"
						class="navigation fsm fwn fcg">
						<a
							title="Read our blog, discover the resource center, and find job opportunities."
							accesskey="8" href="http://www.facebook.com/facebook">About</a> ·
						<a title="Advertise on Facebook."
							href="http://www.facebook.com/campaign/landing.php?placement=pf&amp;campaign_id=402047449186&amp;extra_1=auto">Create
							an Ad</a> · <a title="Create a Page"
							href="http://www.facebook.com/pages/create.php?ref_type=sitefooter">Create
							a Page</a> · <a title="Develop on our platform."
							href="http://developers.facebook.com/?ref=pf">Developers</a> · <a
							title="Make your next career move to our awesome company."
							href="http://www.facebook.com/careers/?ref=pf">Careers</a> · <a
							title="Learn about your privacy and Facebook."
							href="http://www.facebook.com/privacy/explanation">Privacy</a> ·
						<a title="Learn about cookies and Facebook."
							href="http://www.facebook.com/help/cookies">Cookies</a> · <a
							title="Review our terms and policies." accesskey="9"
							href="http://www.facebook.com/policies/?ref=pf">Terms</a> · <a
							title="Visit our Help Center." accesskey="0"
							href="http://www.facebook.com/help/?ref=pf">Help</a>
					</div>
				</div>
			</div>



		</div>
	</div>

</body>
</html>
