<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
    <?php echo $this->headTitle('ProjectName')->setSeparator(' - ')->setAutoEscape(false)?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

    <!-- Le styles -->
    <?php
    
    echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/favicon.ico'
    ))
        ->prependStylesheet($this->basePath() . '/css/map_style14.css')
        ->prependStylesheet($this->basePath() . '/css/map_style13.css')
        ->prependStylesheet($this->basePath() . '/css/map_style12.css')
        ->prependStylesheet($this->basePath() . '/css/map_style11.css')
        ->prependStylesheet($this->basePath() . '/css/map_style10.css')
        ->prependStylesheet($this->basePath() . '/css/map_style9.css')
        ->prependStylesheet($this->basePath() . '/css/map_style8.css')
        ->prependStylesheet($this->basePath() . '/css/map_style7.css')
        ->prependStylesheet($this->basePath() . '/css/map_style6.css')
        ->prependStylesheet($this->basePath() . '/css/map_style5.css')
        ->prependStylesheet($this->basePath() . '/css/map_style4.css')
        ->prependStylesheet($this->basePath() . '/css/map_style3.css')
        ->prependStylesheet($this->basePath() . '/css/map_style2.css')
        ->prependStylesheet($this->basePath() . '/css/map_style1.css')?>

    <!-- Scripts -->
    <?php
    
    echo $this->headScript()
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
    ))
        ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')?>
    <style>
html,body,#map_canvas {
	margin: 0;
	padding: 0;
	height: 100%;
}
</style>
<script
	src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=visualization">
    </script>
<script>
      var map;

      function initialize() {
        var mapOptions = {
          zoom: 2,
          center: new google.maps.LatLng(2.8,-187.3),
          mapTypeId: google.maps.MapTypeId.TERRAIN
        };
        map = new google.maps.Map(document.getElementById('map_canvas'),
              mapOptions);

        // Create a <script> tag and set the USGS URL as the source.
        var script = document.createElement('script');
        // (In this example we use a locally stored copy instead.)
        // script.src = 'http://earthquake.usgs.gov/earthquakes/feed/geojsonp/2.5/week';
        script.src = 'earthquake_GeoJSONP';
        document.getElementsByTagName('head')[0].appendChild(script);
      }

      // Loop through the results array and place a marker for each
      // set of coordinates.
      window.eqfeed_callback = function(results) {
        for (var i = 0; i < results.features.length; i++) {
          var coords = results.features[i].geometry.coordinates;
          var latLng = new google.maps.LatLng(coords[1],coords[0]);
          var marker = new google.maps.Marker({
            position: latLng,
            map: map
          });
        }
      }

  </script>
</head>
<body onload="initialize()"
	class="hasLeftCol home composerExpanded fbx ff4 win Locale_en_US">
	<div class="_li">

		<!-- Header -->
		<div data-referrer="pagelet_bluebar" id="pagelet_bluebar">
			<div class="slim" id="blueBarHolder">
				<div class="fixed_elem" id="blueBar">
					<div role="banner" class="clearfix" id="pageHead">
						<h1 id="pageLogo">
							<a href="http://www.facebook.com/?ref=logo" style="">Facebook</a>
						</h1>
						<div class="notifNegativeBase notifCentered notifGentleAppReceipt"
							id="jewelContainer">
							<div id="fbRequestsJewel"
								class="fbJewel hasNew hasCountMedium showRequests">
								<a aria-owns="fbRequestsFlyout" aria-haspopup="true"
									data-target="fbRequestsFlyout"
									data-gt="{&quot;ua_id&quot;:&quot;jewel:requests&quot;}"
									name="requests" aria-labelledby="requestsCountWrapper"
									role="button" href="#" rel="toggle" class="jewelButton"><span
									id="requestsCountWrapper" class="jewelCount"><span
										id="requestsCountValue">91</span><i class="accessible_elem">
											Requests</i></span></a>
							</div>
							<div id="fbMessagesJewel" class="fbJewel">
								<a aria-owns="fbMessagesFlyout" aria-haspopup="true"
									data-target="fbMessagesFlyout"
									data-gt="{&quot;ua_id&quot;:&quot;jewel:mercurymessages&quot;}"
									name="mercurymessages"
									aria-labelledby="mercurymessagesCountWrapper" role="button"
									href="#" rel="toggle" class="jewelButton"><span
									id="mercurymessagesCountWrapper" class="jewelCount"><span
										id="mercurymessagesCountValue">0</span><i
										class="accessible_elem"> Messages</i></span></a>
							</div>
							<div id="fbNotificationsJewel" class="fbJewel west">
								<a aria-owns="fbNotificationsFlyout" aria-haspopup="true"
									data-target="fbNotificationsFlyout"
									data-gt="{&quot;ua_id&quot;:&quot;jewel:notifications&quot;}"
									onclick="return run_with(this, [&quot;min-notifications-jewel&quot;], function() {MinNotifications.bootstrap(this)});"
									name="notifications"
									aria-labelledby="notificationsCountWrapper" role="button"
									href="#" rel="toggle" class="jewelButton"><span
									id="notificationsCountWrapper" class="jewelCount"><span
										id="notificationsCountValue">0</span><i
										class="accessible_elem"> Notifications</i></span></a>
							</div>
						</div>
						<div id="headNav" class="clearfix">
							<form
								onsubmit="return window.Event &amp;&amp; Event.__inlineSubmit &amp;&amp; Event.__inlineSubmit(this,event)"
								role="search"
								action="http://www.facebook.com/search/results.php"
								name="navSearch" id="navSearch" method="get" class="lfloat">
								<div id="ubypmma2" class="uiTypeahead">
									<div class="wrap">
										<input type="hidden" class="hiddenInput" autocomplete="off">
										<div class="innerWrap">
											<span id="ubypmma3" class="uiSearchInput textInput"><span><input
													type="text" value="Search for people, places and things"
													spellcheck="false" role="combobox"
													aria-owns="typeahead_list_ubypmma2" aria-expanded="false"
													aria-autocomplete="list"
													onfocus="$(&quot;search_first_focus&quot;).value = $(&quot;search_first_focus&quot;).value || +new Date();;Bootloader.loadComponents(&quot;SearchBootloader&quot;, emptyFunction);"
													tabindex="" autocomplete="off"
													placeholder="Search for people, places and things"
													onclick="var q = $(&quot;q&quot;);if (q.value == q.getAttribute(&quot;placeholder&quot;)) {q.focus(); return false;}"
													name="q" id="q" accesskey="/" aria-label="Search"
													maxlength="100" class="inputtext DOMControl_placeholder">
													<button title="Search for people, places and things"
														onclick="var q = $(&quot;q&quot;);if (q.value == q.getAttribute(&quot;placeholder&quot;)) {q.focus(); return false;}"
														type="submit">
														<span class="accessible_elem">Search for people, places
															and things</span>
													</button></span></span>
										</div>
									</div>
									<div id="ubypmma1"
										class="uiTypeaheadView wideSearchTypeaheadView mainSearchTypeaheadView"></div>
								</div>
							</form>
							<div class="rfloat">
								<ul role="navigation" class="clearfix" id="pageNav">
									<li class="navItem firstItem tinyman"><a accesskey="2"
										title="Profile"
										href="http://www.facebook.com/bui.thanhphuong.3?ref=tn_tnmn"
										class="navLink"><img id="profile_pic_header_100000235183823"
											alt=""
											src="%2891%29%20Facebook_files/202907_100000235183823_5803336_q.jpg"
											class="_s0 headerTinymanPhoto _rw img"><span
											class="headerTinymanName">Bui Thanh Phuong</span></a></li>
									<li class="navItem middleItem"><a id="findFriendsNav"
										href="http://www.facebook.com/?sk=ff"
										class="navLink bigPadding">Find Friends</a></li>
									<li id="navHome" class="navItem middleItem"><a accesskey="1"
										href="http://www.facebook.com/?ref=tn_tnmn"
										class="navLink bigPadding">Home</a></li>
									<li id="navAccount"><a aria-labelledby="userNavigationLabel"
										aria-controls="userNavigation" aria-haspopup="1" role="button"
										rel="toggle"
										href="http://www.facebook.com/editaccount.php?ref=mb&amp;drop"
										id="navAccountLink" class="navLink"><div
												id="userNavigationLabel" class="menuPulldown">Account
												Settings</div></a>
										<ul aria-label="Account Menu" role="menu navigation"
											id="userNavigation" class="navigation">
											<li role="menuitem"><a
												href="http://www.facebook.com/campaign/landing.php?placement=tad&amp;campaign_id=264263327005748&amp;extra_1=auto&amp;extra_2=AdvertisingMenu%3ACONTROL"
												class="navSubmenu">Advertise</a></li>
											<li role="menuitem"><a accesskey="6"
												href="http://www.facebook.com/editaccount.php?ref=mb&amp;drop"
												class="navSubmenu">Account Settings</a></li>
											<li role="menuitem"><a accesskey="7"
												href="http://www.facebook.com/settings/?tab=privacy&amp;ref=mb"
												class="navSubmenu">Privacy Settings</a></li>
											<li role="menuitem"><form
													onsubmit="return window.Event &amp;&amp; Event.__inlineSubmit &amp;&amp; Event.__inlineSubmit(this,event)"
													action="http://www.facebook.com/logout.php" method="post"
													id="logout_form">
													<input type="hidden" autocomplete="off" value="AQDQF8w2"
														name="fb_dtsg"><input type="hidden" value="mb" name="ref"
														autocomplete="off"><input type="hidden"
														value="AfchoXD2CgC6oXXa" name="h" autocomplete="off"><label
														class="uiLinkButton navSubmenu"><input type="submit"
														value="Log Out"></label>
												</form></li>
											<li class="menuDivider"></li>
											<li role="menuitem"><a rel="async"
												ajaxify="http://www.facebook.com/help/ajax/contextual/?page_type=364455653583099"
												target="_blank" id="navHelpCenter"
												href="http://www.facebook.com/help/?ref=drop"
												class="navSubmenu"><div class="clearfix">
														<div class="lfloat">Help</div>
														<img width="16" height="11" alt=""
															src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
															class="rfloat uiLoadingIndicatorAsync img">
													</div></a></li>
										</ul></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		



	</div>
	<div  style="width:300px; height:300px;" >
	<div style="width:100%; height:100%"  id="map_canvas"></div>
	</div>
</body>
</html>
