<div id="leftColContainer">
	<div id="leftCol">
		
		<div data-referrer="pagelet_navigation" id="pagelet_navigation">
			<div id="sideNav" data-gt="{&quot;ref&quot;:&quot;bookmarks&quot;}"
				class="uiFutureSideNav" role="navigation" aria-label="Navigation">
				<div id="pagelet_pinned_nav" data-referrer="pagelet_pinned_nav">
					<div id="pinnedNav" class="homeSideNav">
						<h4 class="navHeader">FAVORITES</h4>
						<div class="mts mbm droppableNav">
							<ul
								data-gt="{&quot;nav_items_count&quot;:&quot;6&quot;,&quot;nav_section&quot;:&quot;pinnedNav&quot;}"
								class="uiSideNav">
								<li id="navItem_app_156203961126022"
									class="sideNavItem stat_elem"><div class="buttonWrap"></div> <a
									data-gt="{&quot;bmid&quot;:&quot;156203961126022&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AauTDzN3uLIi4YHUYt5xZCPIIXZUEl-dTVKhLaHLSxzSq4c_iJzVbKpAZ1EqlFtbxSszLdsQ8Ng6e0tw7nzAMUM9&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;1&quot;}"
									title="" href="http://www.facebook.com/?sk=welcome"
									class="item clearfix"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_1a6dlz sx_b7393d"></i></span>
											<div class="linkWrap noCount">Welcome</div>
										</div></a></li>
								<li id="navItem_app_4748854339"
									class="sideNavItem stat_elem selectedItem open"><div
										class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1"
													aria-label="Edit News Feed" title="Edit" role="button"
													href="#" class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Edit Settings" class="uiMenuItem"><a
																rel="dialog"
																href="http://www.facebook.com/ajax/feed/edit_options_dialog.php"
																tabindex="0" role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Edit Settings</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;4748854339&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AaurrtxV6m4nhjsG9W1VrY1Hx14r0p-4lwfWJpmRDJ7-2cmto7UVD2jRamkYAWIRHSM&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;2&quot;}"
									title="" href="http://www.facebook.com/?sk=nf"
									class="item clearfix"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_6quz4z sx_9c9117"></i></span>
											<div class="linkWrap noCount">News Feed</div>
										</div></a></li>
								<li id="navItem_app_217974574879787"
									class="sideNavItem stat_elem"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit Messages"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Remove from Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Remove from Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;217974574879787&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;2&quot;,&quot;coeff2_info&quot;:&quot;Aav1iT5k4dBbi7k3_BkEKK3F7ZpXMQi0PkyYWjEGEMCsBobNMUU2aemoj-Y5giZKgBS2TlsgpxxoCOhg6uhDmInh&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;3&quot;}"
									title="" href="http://www.facebook.com/messages/"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count uiSideNavCount"><span class="countValue fss">2</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_7uj4ry sx_ada3a2"></i></span>
											<div class="linkWrap hasCount">Messages</div>
										</div></a>
									<ul>
										<li id="navItem_other"><a
											href="http://www.facebook.com/messages/other/"
											class="subitem clearfix"><div class="rfloat">
													<img width="16" height="11" alt=""
														src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
														class="uiLoadingIndicatorAsync img"><span
														class="count uiSideNavCount"><span class="countValue fss">1</span><span
														class="maxCountIndicator"></span></span>
												</div>
												<div>
													<div class="linkWrap hasCount">Other</div>
												</div></a></li>
									</ul> <span class="mover hidden_elem"></span></li>
								<li id="navItem_app_2344061033" class="sideNavItem stat_elem"><div
										class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit Events"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Remove from Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Remove from Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;2344061033&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AausMPS3OW43-lhlox35Eo60m4NY8GUTX-dp3LIg63-UUgV6IOcQSpPPAzN2nBNXQwQ&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;4&quot;}"
									title="" href="http://www.facebook.com/events/list"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><img width="15" height="16" alt=""
												src="%2891%29%20Facebook_files/vdO3Bhuj5K8.png" class="img"></span>
											<div class="linkWrap noCount">Events</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_app_2305272732" class="sideNavItem stat_elem"><div
										class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit Photos"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Remove from Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Remove from Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;2305272732&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AatCCB8gUKbdDzU4_T8RQhx6R-dLTDb3_iiqpXuUBRwjRXXSJpQzQ5WYJHvuflB2I5Y&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;5&quot;}"
									title=""
									href="http://www.facebook.com/bui.thanhphuong.3/photos"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_2vmry3 sx_beccc5"></i></span>
											<div class="linkWrap noCount">Photos</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_app_2356318349" class="sideNavItem stat_elem"><div
										class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1"
													aria-label="Edit Find Friends" title="Edit" role="button"
													href="#" class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Remove from Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Remove from Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;2356318349&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;91&quot;,&quot;coeff2_info&quot;:&quot;Aavl3D1JH3OaSuqml4T-bbb21Jm5MJMdHuOdmkn2qzyxjprGblN2kbGFUZInnWabKuA&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;6&quot;}"
									title="Find Friends" href="http://www.facebook.com/?sk=ff"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count uiSideNavCount"><span class="countValue fss">20</span><span
												class="maxCountIndicator">+</span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_tiitwu sx_cc1db2"></i></span>
											<div class="linkWrap hasCount">Find Friends</div>
										</div></a><span class="mover hidden_elem"></span></li>
							</ul>
							<div class="actionLinks stat_elem">
								<a data-endpoint="/ajax/bookmark/edit/" href="#"
									class="navEditDone"><span class="navEdit">Edit</span><span
									class="navDone">Done</span></a><span class="loadingIndicator"></span>
							</div>
						</div>
					</div>
				</div>
				<div id="pagelet_bookmark_nav" data-referrer="pagelet_bookmark_nav">
					<div>
						<div id="appsNav" class="homeSideNav">
							<h4 class="navHeader">APPS</h4>
							<ul
								data-gt="{&quot;nav_items_count&quot;:&quot;6&quot;,&quot;nav_section&quot;:&quot;appsNav&quot;}"
								class="uiSideNav mts mbm nonDroppableNav">
								<li id="navItem_app_140332009231"
									class="sideNavItem stat_elem expander"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1"
													aria-label="Edit App Center" title="Edit" role="button"
													href="#" class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;140332009231&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;type&quot;:&quot;click2appcenter&quot;,&quot;coeff2_info&quot;:&quot;Aau5HKfjKZQBE15kK9oEd53CdQuZJgk-8piPmYx8LDNKxSLwD4ROW-wb-iVH1LArkA8BZ-KpdMrvkzKGBlFsNr3a&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;1&quot;}"
									title=""
									href="http://www.facebook.com/appcenter/?from_bookmark=1"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_6quz4z sx_b7e554"></i></span>
											<div class="linkWrap noCount">App Center</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_app_261369767293002"
									class="sideNavItem stat_elem">
									<div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1"
													aria-label="Edit Games Feed" title="Edit" role="button"
													href="#" class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;261369767293002&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;10&quot;,&quot;coeff2_info&quot;:&quot;AatWXC2310gxYPgEZ9z2mwptYKePmr_XB1DTjfZ_8VIiWHoG-3uD8CphTSA3h7C39f2Aoy_eMao4fgcEq_Gdq27e&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;2&quot;}"
									title="" href="http://www.facebook.com/apps/feed"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count uiSideNavCount"><span class="countValue fss">10</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_2vmry3 sx_d03f36"></i></span>
											<div class="linkWrap hasCount">Games Feed</div>
										</div></a><span class="mover hidden_elem"></span>
								</li>
								<li id="navItem_app_119960514742544"
									class="sideNavItem stat_elem"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit Music"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;119960514742544&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;Aau1nMgtdeEi9b6gWBaXyQG787-hg_jmYegrNXAVav8VXbIrRHDjcbXDKzVZMDFuWnUcD6PZrmWsgyZ90qGSXX0r&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;3&quot;}"
									title="" href="http://www.facebook.com/music"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_2vmry3 sx_21e6a7"></i></span>
											<div class="linkWrap noCount">Music</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_app_2347471856" class="sideNavItem stat_elem"><div
										class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit Notes"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;2347471856&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;Aav6Hf_SdCohPruZMK_dKUqec29DkkFchQkZWVcbyrLD3XHGRka78CzxkdP4WVjRdSw&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;4&quot;}"
									title="" href="http://www.facebook.com/notes/"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_2vmry3 sx_eafddd"></i></span>
											<div class="linkWrap noCount">Notes</div>
										</div></a>
									<ul>
										<li id="navItem_notes_pages"><a
											href="http://www.facebook.com/notes/pages/"
											class="subitem clearfix"><div class="rfloat">
													<img width="16" height="11" alt=""
														src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
														class="uiLoadingIndicatorAsync img"><span
														class="count hidden_elem uiSideNavCount"><span
														class="countValue fss">0</span></span>
												</div>
												<div>
													<div class="linkWrap noCount">Pages' Notes</div>
												</div></a></li>
										<li id="navItem_notes_drafts"><a
											href="http://www.facebook.com/notes/drafts/"
											class="subitem clearfix"><div class="rfloat">
													<img width="16" height="11" alt=""
														src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
														class="uiLoadingIndicatorAsync img"><span
														class="count hidden_elem uiSideNavCount"><span
														class="countValue fss">0</span></span>
												</div>
												<div>
													<div class="linkWrap noCount">My Drafts</div>
												</div></a></li>
										<li id="navItem_notes_tagged"><a
											href="http://www.facebook.com/notes/tagged/"
											class="subitem clearfix"><div class="rfloat">
													<img width="16" height="11" alt=""
														src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
														class="uiLoadingIndicatorAsync img"><span
														class="count hidden_elem uiSideNavCount"><span
														class="countValue fss">0</span></span>
												</div>
												<div>
													<div class="linkWrap noCount">Notes About Me</div>
												</div></a></li>
										<li id="navItem_notes_me"><a
											href="http://www.facebook.com/notes/me/"
											class="subitem clearfix"><div class="rfloat">
													<img width="16" height="11" alt=""
														src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
														class="uiLoadingIndicatorAsync img"><span
														class="count hidden_elem uiSideNavCount"><span
														class="countValue fss">0</span></span>
												</div>
												<div>
													<div class="linkWrap noCount">My Notes</div>
												</div></a></li>
									</ul> <span class="mover hidden_elem"></span></li>
								<li id="navItem_app_2309869772" class="sideNavItem stat_elem"><div
										class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit Links"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;2309869772&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;type&quot;:&quot;click2canvas&quot;,&quot;coeff2_info&quot;:&quot;AavBNz4o8rZQZWT7e830u5J4fm7PvOYD2tnNuV9PSM_LXuDLvzShPf2sLnMFy3_mft8&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;5&quot;}"
									title="" href="http://www.facebook.com/?sk=app_2309869772"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_2vmry3 sx_a25cf9"></i></span>
											<div class="linkWrap noCount">Links</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_app_183217215062060"
									class="sideNavItem stat_elem"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit Pokes"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;183217215062060&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AauH04ot9GLgxX-VKuOMCt5bAYBLdo1It2H_7Gxa0xqwlrSAZbL3vTWFdGSOzNoeJ98c04nVr853qug0-dH7Y8qN&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;6&quot;}"
									title="" href="http://www.facebook.com/pokes"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_6quz4z sx_0bc8e8"></i></span>
											<div class="linkWrap noCount">Pokes</div>
										</div></a><span class="mover hidden_elem"></span></li>
							</ul>
						</div>
						<div id="groupsNav" class="homeSideNav">
							<h4 class="navHeader">GROUPS</h4>
							<ul
								data-gt="{&quot;nav_items_count&quot;:&quot;4&quot;,&quot;nav_section&quot;:&quot;groupsNav&quot;}"
								class="uiSideNav mts mbm nonDroppableNav">
								<li id="navItem_group_519834054699098"
									class="sideNavItem stat_elem"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1"
													aria-label="Edit H?i nh?ng ngu?i thích an chay"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
															<li data-label="Edit Settings" class="uiMenuItem"><a
																rel="dialog"
																href="http://www.facebook.com/ajax/groups/membership/subscribe_get.php?group_id=519834054699098"
																tabindex="-1" role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Edit Settings</span></a></li>
															<li class="uiMenuSeparator"></li>
															<li data-label="Leave Group" class="uiMenuItem"><a
																rel="dialog"
																href="http://www.facebook.com/ajax/bookmark/groups/leave/?group_id=519834054699098"
																tabindex="-1" role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Leave Group</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;519834054699098&quot;,&quot;fbtype&quot;:&quot;69&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AatRBfFQs6JFJEr9P7DBWSA9DoNcLdEyitiFJKFsDbxZc2lB0CJlgRwd3ZQNTVRPBYnsC8PdtlO_BQFORSNRcch5&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;1&quot;}"
									title="H?i nh?ng ngu?i thích an chay"
									href="http://www.facebook.com/groups/vegevill/"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_9sdxgb sx_961b7d"></i></span>
											<div class="linkWrap noCount">H?i nh?ng ngu?i thích an chay</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_group_167606749934601"
									class="sideNavItem stat_elem"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit Beeric"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
															<li data-label="Edit Settings" class="uiMenuItem"><a
																rel="dialog"
																href="http://www.facebook.com/ajax/groups/membership/subscribe_get.php?group_id=167606749934601"
																tabindex="-1" role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Edit Settings</span></a></li>
															<li class="uiMenuSeparator"></li>
															<li data-label="Leave Group" class="uiMenuItem"><a
																rel="dialog"
																href="http://www.facebook.com/ajax/bookmark/groups/leave/?group_id=167606749934601"
																tabindex="-1" role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Leave Group</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;167606749934601&quot;,&quot;fbtype&quot;:&quot;69&quot;,&quot;count&quot;:&quot;1&quot;,&quot;coeff2_info&quot;:&quot;AauJmCvTtLBtv1rfPokM6F78N9Rou6QhbrxmEaedzQwzBMfZWI24_XO8CoP6_ZcUZviDcDBgY9dvuWo_Xt1u_S1W&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;2&quot;}"
									title="" href="http://www.facebook.com/groups/167606749934601/"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count uiSideNavCount"><span class="countValue fss">1</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_7uj4ry sx_056073"></i></span>
											<div class="linkWrap hasCount">Beeric</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_group_226618834060591"
									class="sideNavItem stat_elem"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1"
													aria-label="Edit H?i nh?ng ngu?i thích tra t?n ngu?i khác b?ng gi?ng ca"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
															<li data-label="Edit Settings" class="uiMenuItem"><a
																rel="dialog"
																href="http://www.facebook.com/ajax/groups/membership/subscribe_get.php?group_id=226618834060591"
																tabindex="-1" role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Edit Settings</span></a></li>
															<li class="uiMenuSeparator"></li>
															<li data-label="Leave Group" class="uiMenuItem"><a
																rel="dialog"
																href="http://www.facebook.com/ajax/bookmark/groups/leave/?group_id=226618834060591"
																tabindex="-1" role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Leave Group</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;226618834060591&quot;,&quot;fbtype&quot;:&quot;69&quot;,&quot;count&quot;:&quot;25&quot;,&quot;coeff2_info&quot;:&quot;AavXnFLFkLdgz85mqE1w8rm04wdw6cVm0gIkQnhpYs2Dc07HltQa5F-zIToHv00IWjvtNwseal6upl7BG_5tccOY&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;3&quot;}"
									title="H?i nh?ng ngu?i thích tra t?n ngu?i khác b?ng gi?ng ca"
									href="http://www.facebook.com/groups/226618834060591/"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count uiSideNavCount"><span class="countValue fss">20</span><span
												class="maxCountIndicator">+</span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_7uj4ry sx_056073"></i></span>
											<div class="linkWrap hasCount">H?i nh?ng ngu?i thích tra t?n
												ngu?i khác b?ng gi?ng ca</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_app_230259100322928"
									class="sideNavItem stat_elem"><div class="buttonWrap"></div> <a
									data-gt="{&quot;bmid&quot;:&quot;230259100322928&quot;,&quot;fbtype&quot;:&quot;128&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;Aatctrnx5WmnxOdfe4Open89RWMeUzzDV9CTR7PBVGZqHUqTw2yEnu5pN9oDHxsmCQoBsq9FqRloWxDQYl3emMOZ&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;4&quot;}"
									rel="async" title="Create Group..."
									href="http://www.facebook.com/ajax/groups/create_get.php?ref=bookmarks"
									class="item clearfix"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_6quz4z sx_e60393"></i></span>
											<div class="linkWrap noCount">Create Group...</div>
										</div></a></li>
							</ul>
						</div>
						<div id="interestsNav" class="homeSideNav">
							<h4 class="navHeader hidden_elem">
								<a href="http://www.facebook.com/bookmarks/interests"><div
										class="clearfix">
										<div class="lfloat">INTERESTS</div>
										<span class="mrm rfloat"><div class="bookmarksNavSeeAll">MORE</div>
											<img width="16" height="11" alt=""
											src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
											class="uiLoadingIndicatorAsync img"></span>
									</div></a>
							</h4>
							<ul
								data-gt="{&quot;nav_items_count&quot;:&quot;0&quot;,&quot;nav_section&quot;:&quot;interestsNav&quot;}"
								class="uiSideNav mts mbm nonDroppableNav"></ul>
						</div>
						
						<div id="listsNav" class="homeSideNav belowThreshold">
							<h4 class="navHeader">
								<a href="http://www.facebook.com/bookmarks/lists"><div
										class="clearfix">
										<div class="lfloat">FRIENDS</div>
										<span class="mrm rfloat"><div class="bookmarksNavSeeAll">MORE</div>
											<img width="16" height="11" alt=""
											src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
											class="uiLoadingIndicatorAsync img"></span>
									</div></a>
							</h4>
							<ul
								data-gt="{&quot;nav_items_count&quot;:&quot;3&quot;,&quot;nav_section&quot;:&quot;listsNav&quot;}"
								class="uiSideNav mts mbm nonDroppableNav">
								<li id="navItem_fl_478653708819131"
									class="sideNavItem stat_elem"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1"
													aria-label="Edit Close Friends" title="Edit" role="button"
													href="#" class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;478653708819131&quot;,&quot;fbtype&quot;:&quot;17&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AasKPBUeRmMdpMgGltyWJaIptXVVkj77rZUJMxv9FCSsz7rBoNqII_l3y_C4ZXKE8Lbrq4oP_b_Zr2Cr4LKV-aw1&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;1&quot;}"
									title="Close Friends"
									href="http://www.facebook.com/lists/478653708819131"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_6quz4z sx_e34de1"></i></span>
											<div class="linkWrap noCount">Close Friends</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_fl_478653712152464"
									class="sideNavItem stat_elem"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit Family"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
															<li class="uiMenuSeparator"></li>
															<li data-label="Archive List" class="uiMenuItem"><a
																rel="dialog"
																href="http://www.facebook.com/ajax/friends/lists/archive/?flid=478653712152464"
																tabindex="-1" role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Archive List</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;478653712152464&quot;,&quot;fbtype&quot;:&quot;17&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;AavEIOFowh4fyj8BCXVnudVoprnvCvHcmzMtxcvpWW6yKncyW6OQzfoaMF9F9Aj1uRiGBKn1EvW1Wf1blD5CqNhu&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;2&quot;}"
									title="" href="http://www.facebook.com/lists/478653712152464"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_6quz4z sx_bdeff5"></i></span>
											<div class="linkWrap noCount">Family</div>
										</div></a><span class="mover hidden_elem"></span></li>
								<li id="navItem_fl_103837632967409"
									class="sideNavItem stat_elem"><div class="buttonWrap">
										<div
											class="uiSelector inlineBlock mas bookmarksMenuButton uiSideNavEditButton">
											<div class="wrap">
												<a rel="toggle" aria-haspopup="1" aria-label="Edit friends"
													title="Edit" role="button" href="#"
													class="uiSelectorButton uiCloseButton"></a>
												<div class="uiSelectorMenuWrapper uiToggleFlyout">
													<div class="uiMenu uiSelectorMenu" role="menu">
														<ul class="uiMenuInner">
															<li data-label="Add to Favorites"
																class="uiMenuItem favorite"><a href="#" tabindex="0"
																role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Add to Favorites</span></a></li>
															<li data-label="Rearrange" class="uiMenuItem rearrange"><a
																href="#" tabindex="-1" role="menuitem"
																class="itemAnchor"><span class="itemLabel fsm">Rearrange</span></a></li>
															<li class="uiMenuSeparator"></li>
															<li data-label="Delete List" class="uiMenuItem"><a
																rel="dialog"
																href="http://www.facebook.com/friends/edit/ajax/delete_list_dialog.php?flid=103837632967409"
																tabindex="-1" role="menuitem" class="itemAnchor"><span
																	class="itemLabel fsm">Delete List</span></a></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div> <a
									data-gt="{&quot;bmid&quot;:&quot;103837632967409&quot;,&quot;fbtype&quot;:&quot;17&quot;,&quot;count&quot;:&quot;0&quot;,&quot;coeff2_info&quot;:&quot;Aat42o_RgJCcQOTVQ0rUdXPInl-TDCItfydJVObHPmrNj8wAWXL-fxKvFed_wAG-05k2JfAsSjXX5fxkbY9orj5G&quot;,&quot;coeff2_registry_key&quot;:&quot;0016&quot;,&quot;coeff2_action&quot;:&quot;3&quot;,&quot;coeff2_pv_signature&quot;:&quot;1211441286&quot;,&quot;rank&quot;:&quot;3&quot;}"
									title="" href="http://www.facebook.com/lists/103837632967409"
									class="item clearfix sortableItem"><div class="rfloat">
											<img width="16" height="11" alt=""
												src="%2891%29%20Facebook_files/GsNJNwuI-UM.gif"
												class="uiLoadingIndicatorAsync img"><span
												class="count hidden_elem uiSideNavCount"><span
												class="countValue fss">0</span><span
												class="maxCountIndicator"></span></span><span class="grip"></span>
										</div>
										<div>
											<span class="imgWrap"><i class="img sp_6quz4z sx_a0b389"></i></span>
											<div class="linkWrap noCount">friends</div>
										</div></a><span class="mover hidden_elem"></span></li>
							</ul>
						</div>
						<a id="ubyptq81" href="#" class="moreSectionsLink"><span
							class="uiMoreLinkText">MORE</span><i
							class="uiMoreLinkCaret img sp_2vmry3 sx_f8318f"></i></a>
					</div>
				</div>
			</div>
		</div>
	</div>







</div>
