<div class="gradient">
	<div class="gradientContent">
		<div class="clearfix fbIndexFeaturedRegistration">
		
<!-- Panel Left -->
			<div class="feature lfloat">
				<div class="clearfix fbIndexMobile">
					<a rel="dialog" href="#" tabindex="-1" class="lfloat">
						<img width="97" height="205" alt="" src="<?php echo $this->basePath() . "/images/phone.png" ?>" class="mtm phoneImage img">
					</a>
					<div class="clearfix rightSide rfloat">
						<div class="lfloat">
							<div class="title fsl fwb fcb">Heading out? Stay connected</div>
							<div class="subtitle fsm fwn fcg">Visit facebook.com on your mobile phone.</div>
						</div>
						<a rel="dialog" href="#" class="mrl mobileButton rfloat uiButton">
							<span class="uiButtonText">Get Facebook Mobile</span></a>
					</div>
				</div>
			</div>	
<!-- Panel Right -->
			<div class="signupForm rfloat">
				<div class="mbm phm headerTextContainer">
					<div class="mbs mainTitle fsl fwb fcb"><?php echo $this->translate('Sign Up')?></div>
					<div class="mbm subtitle fsm fwn fcg"><?php echo $this->translate('It&apos;s free and always will be.')?></div>
				</div>
				<div id="registration_container">
					<div data-referrer="simple_registration_form">
						<div class="simple_registration_container" id="simple_registration_container">
							<div id="reg_box">
								<form id="reg" name="reg" method="post" action="/account/register" onsubmit="return true;">
									<div class="large_form" id="reg_form_box">
										<table cellspacing="0" cellpadding="1" class="uiGrid editor">
											<tbody>
												<tr>
													<td class="label">
														<label for="firstname"><?php echo $this->translate('First Name:')?></label>
													</td>
													<td>
														<div class="field_container">
															<input type="text" name="firstname" id="firstname" class="inputtext" title="">
														</div>
													</td>
												</tr>
												<tr>
													<td class="label">
														<label for="lastname"><?php echo $this->translate('Last Name:')?></label>
													</td>
													<td>
														<div class="field_container">
															<input type="text" name="lastname" id="lastname" class="inputtext">
														</div>
													</td>
												</tr>
												<tr>
													<td class="label">
														<label for="reg_email__"><?php echo $this->translate('Your Email:')?></label>
													</td>
													<td>
														<div class="field_container">
															<input type="text" name="reg_email__" id="reg_email__" class="inputtext">
														</div>
													</td>
												</tr>
												<tr>
													<td class="label">
														<label for="reg_email_confirmation__"><?php echo $this->translate('Re-enter Email:')?></label>
													</td>
													<td>
														<div class="field_container">
															<input type="text" name="reg_email_confirmation__" id="reg_email_confirmation__" class="inputtext">
														</div>
													</td>
												</tr>
												<tr>
													<td class="label">
														<label for="reg_passwd__"><?php echo $this->translate('New Password:')?></label>
													</td>
													<td>
														<div class="field_container">
															<input type="password" value="" name="reg_passwd__" id="reg_passwd__" class="inputtext">
														</div>
													</td>																		
												</tr>
												<tr>
													<td class="label"><?php echo $this->translate('I am:')?></td>
													<td>
														<div class="field_container">																			
															<select id="sex" name="sex" class="select">
																<option value="0"><?php echo $this->translate('Select Sex:')?></option>
																<option value="1"><?php echo $this->translate('Female')?></option>
																<option value="2"><?php echo $this->translate('Male')?></option>
															</select>
														</div>
													</td>
												</tr>
												<tr>
													<td class="label"><?php echo $this->translate('Birthday:')?></td>
													<td>
														<div class="field_container">
														<select class="" id="birthday_month"  onchange="selectMonth()" name="birthday_month">
															<option value="-1"><?php echo $this->translate('Month:')?></option>
															<option value="1"><?php echo $this->translate('Jan')?></option>
															<option value="2"><?php echo $this->translate('Feb')?></option>
															<option value="3"><?php echo $this->translate('Mar')?></option>
															<option value="4"><?php echo $this->translate('Apr')?></option>
															<option value="5"><?php echo $this->translate('May')?></option>
															<option value="6"><?php echo $this->translate('Jun')?></option>
															<option value="7"><?php echo $this->translate('Jul')?></option>
															<option value="8"><?php echo $this->translate('Aug')?></option>
															<option value="9"><?php echo $this->translate('Sep')?></option>
															<option value="10"><?php echo $this->translate('Oct')?></option>
															<option value="11"><?php echo $this->translate('Nov')?></option>
															<option value="12"><?php echo $this->translate('Dec')?></option>
														</select> 
														<select class="" id="birthday_day" name="birthday_day">
															<option value="-1"><?php echo $this->translate('Day:')?></option>
															<option value="1">1</option>
															<option value="2">2</option>
															<option value="3">3</option>
															<option value="4">4</option>
															<option value="5">5</option>
															<option value="6">6</option>
															<option value="7">7</option>
															<option value="8">8</option>
															<option value="9">9</option>
															<option value="10">10</option>
															<option value="11">11</option>
															<option value="12">12</option>
															<option value="13">13</option>
															<option value="14">14</option>
															<option value="15">15</option>
															<option value="16">16</option>
															<option value="17">17</option>
															<option value="18">18</option>
															<option value="19">19</option>
															<option value="20">20</option>
															<option value="21">21</option>
															<option value="22">22</option>
															<option value="23">23</option>
															<option value="24">24</option>
															<option value="25">25</option>
															<option value="26">26</option>
															<option value="27">27</option>
															<option value="28">28</option>
															<option value="29">29</option>
															<option value="30">30</option>
															<option value="31">31</option>
														</select>
														<select id="birthday_year" onchange="selectYear()" name="birthday_year">
															<option value="-1">Year:</option>
															<?php
																$year = date("Y");
																for ($i = $year; $i >= $year - 120; $i--){
																	echo "<option value=\"" . $i . "\">" . $i . "</option>";				
																}										 
															?>															
														</select>
													</div>
												</td>
											</tr>											
											<tr>
												<td class="label"></td>
												<td>
													<div id="ppt_container" class="fbRegistrationPPT">
														<p class="privacy_policy_text text"><?php echo $this->translate('By clicking Sign Up, you agree to our')?> <a rel="nofollow" target="_blank" href="/terms.php">Terms</a> and that you have read our <a rel="nofollow" target="_blank" href="/policy.php">Data Use Policy</a>, including our <a rel="nofollow" target="_blank" href="/help/cookies/">Cookie Use</a>.</p>
													</div>
												</td>
											</tr>
										</tbody>
									</table>
										<div class="reg_btn clearfix">
											<label for="ujyw3k41" class="uiButton uiButtonSpecial">
												<input type="submit" id="btnSignUp" value="<?php echo $this->translate('Sign Up')?>">
											</label>
										</div>
									</div>
								</form>
								
								<div class="" id="reg_error" style="opacity: 1; height: auto;">
									<div id="reg_error_inner">
										<form>Sorry, it looks like btphuong2345@yahoo.com belongs to an existing account. Would you like to <label class="uiLinkButton"><input type="submit" value="claim this email address"></label>?</form>
									</div>
								</div>
								<div class="tos_container" id="tos_container">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Languages -->
<?php echo $this->render('layout/languages.phtml') ?>	
